USE Techshop;
-- retrieving  a list of all orders along with customer information  for each order.
SELECT 
    Orders.OrderID, 
    Orders.OrderDate, 
    Customers.FirstName, 
    Customers.LastName, 
    Customers.Email
FROM Orders 
JOIN Customers ON Orders.CustomerID = Customers.CustomerID;

-- finding the total revenue generated by each electronic gadget product
SELECT 
    Products.ProductName, 
    SUM(Products.Price * OrderDetails.Quantity) AS TotalRevenue
FROM OrderDetails
JOIN Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY Products.ProductName
ORDER BY TotalRevenue DESC;

-- List all customers who have made at least one purchase
SELECT DISTINCT Customers.FirstName, Customers.LastName, Customers.Email, Customers.Phone
FROM Customers
JOIN Orders ON Customers.CustomerID = Orders.CustomerID;

-- The one with the highest total quantity ordered
SELECT Products.ProductName, SUM(OrderDetails.Quantity) AS TotalQuantityOrdered
FROM OrderDetails
JOIN Products ON OrderDetails.ProductID = Products.ProductID
GROUP BY Products.ProductName
ORDER BY TotalQuantityOrdered DESC
LIMIT 1;

-- Retrieving a list of electronic gadgets along with their corresponding categories.
ALTER TABLE Products ADD COLUMN Category VARCHAR(50);
UPDATE Products 
SET Category = 
    CASE 
        WHEN ProductName IN ('Laptop', 'Tablet') THEN 'Computing Devices'
        WHEN ProductName IN ('Smartphone', 'Smartwatch','Wireless Earbuds') THEN 'Mobile & Wearable'
        WHEN ProductName IN ('Headphones') THEN 'Audio Devices'
        WHEN ProductName IN ('Gaming Console') THEN 'Gaming'
        WHEN ProductName IN ('Keyboard', 'Mouse') THEN 'Computer Accessories'
        WHEN ProductName IN ('Monitor') THEN 'Display & Peripherals'
        WHEN ProductName IN ('External Hard Drive') THEN 'Storage Devices'
        ELSE 'Other Electronics'
    END;

SELECT ProductName, Category 
FROM Products;
-- the average order value for each customer
SELECT CustomerID, AVG(TotalAmount) AS AvgOrderValue 
FROM Orders 
GROUP BY CustomerID;

-- Order with the Highest Total Revenue
SELECT OrderID, TotalAmount 
FROM Orders 
ORDER BY TotalAmount DESC 
LIMIT 1;

-- Find customers who purchased a specific electronic gadget
SELECT ProductID, COUNT(*) AS TimesOrdered  
FROM OrderDetails  
GROUP BY ProductID;


-- Finding customers who purchased a specific electronic gadget
SELECT DISTINCT Customers.CustomerID, Customers.FirstName, Customers.LastName  
FROM Customers  
JOIN Orders ON Customers.CustomerID = Orders.CustomerID  
JOIN OrderDetails ON Orders.OrderID = OrderDetails.OrderID  
JOIN Products ON OrderDetails.ProductID = Products.ProductID  
WHERE Products.ProductName = 'Tablet';

-- Total revenue from orders within a specific time period
SELECT SUM(TotalAmount) AS TotalRevenue  
FROM Orders  
WHERE OrderDate BETWEEN '2025-03-01' AND '2025-03-15'; 


