use TechShop;
--  Customers who have not placed any orders
SELECT FirstName, LastName  
FROM Customers  
WHERE CustomerID NOT IN (SELECT DISTINCT CustomerID FROM Orders);

--  Total number of products available for sale
SELECT COUNT(*) AS TotalProducts FROM Products;

-- Total revenue generated by TechShop
SELECT SUM(TotalAmount) AS TotalRevenue FROM Orders;

-- Average quantity ordered for products in a specific category
SELECT AVG(OrderDetails.Quantity) AS AvgQuantity  
FROM OrderDetails  
JOIN Products ON OrderDetails.ProductID = Products.ProductID  
WHERE Products.Category = 'Computer Accessories';

-- Calculating Total Revenue for a Specific Customer
SELECT SUM(TotalAmount) AS TotalRevenue  
FROM Orders  
WHERE CustomerID = 4;  

-- Finding Customers Who Placed the Most Orders
SELECT Customers.FirstName, Customers.LastName, COUNT(Orders.OrderID) AS OrderCount  
FROM Customers  
JOIN Orders ON Customers.CustomerID = Orders.CustomerID  
GROUP BY Customers.CustomerID  
ORDER BY OrderCount DESC  
LIMIT 1;  

-- finding the Most Popular Product Category
SELECT Products.Category, SUM(OrderDetails.Quantity) AS TotalQuantityOrdered  
FROM Products  
JOIN OrderDetails ON Products.ProductID = OrderDetails.ProductID  
GROUP BY Products.Category  
ORDER BY TotalQuantityOrdered DESC  
LIMIT 1;  

--  Finding the Customer Who Spent the Most on Electronic Gadgets
SELECT C.FirstName, C.LastName, SUM(Od.Quantity * P.Price) AS TotalSpent  
FROM Customers C  
JOIN Orders O ON C.CustomerID = O.CustomerID  
JOIN OrderDetails Od ON O.OrderID = Od.OrderID  
JOIN Products P ON Od.ProductID = P.ProductID  
WHERE P.Category = 'Audio Devices'  
GROUP BY C.CustomerID  
ORDER BY TotalSpent DESC  
LIMIT 1;  

-- Calculating the Average Order Value for All Customers
SELECT AVG(TotalAmount) AS AverageOrderValue  
FROM Orders;  

-- finding the total number of orders placed by each customer and list their names along with the order count.
SELECT C.FirstName, C.LastName, COUNT(O.OrderID) AS OrderCount  
FROM Customers C  
JOIN Orders O ON C.CustomerID = O.CustomerID  
GROUP BY C.CustomerID;  





